### ISSUE TITLE
no longer working

### ISSUE THREAD

**Issue by kzargonaute** [Tonexus/poe-scambot#17]
This was working fantastic until a few days ago, where all of a sudden it stopped working whenever you press "Start". You get this error:

Exception in Tkinter callback
Traceback (most recent call last):
  File "D:\Downloads\poe-scambot-master (1)\poe-scambot-master\scambot.pyw", line 199, in start_parsing
    self.queue_parse_ids.put(requests.get(constants.NEXT_API).json()['nextChangeId'])
KeyError: 'nextChangeId'

Was something changed in the API that made it so it no longer works?

**Comment by Tonexus** [comment]
It seems like the API has changed from using `nextChangeId` to `next_change_id`. I just pushed out a hotfix.
