### ISSUE TITLE
Feature Request: Currency Equivalence

### ISSUE THREAD

**Issue by charlarpoe1** [Tonexus/poe-scambot#2]
It appears you are only searching for currency type by name in the JSON. how about converting ex down to chaos down to alchemy/fuse/jewellers at the very least?

I don't want to bog down development with using, say, poe.ninja's most recent values.

**Comment by Tonexus** [comment]
I was thinking pretty heavily about this, but I couldn't come up with a good way to get accurate conversion rates in real time. Even poe.trade has this problem, as, for instance, it regularly misprices the ex to chaos ratio. That being said, it is a feature that I do want to implement, so I will investigate my options further. Specifically, do you know if poe.ninja has an API for grabbing the "to chaos" conversions?

**Comment by charlarpoe1** [comment]
I'm unsure if it provides a conversion value in its API. but at the least an .ini file to set your own rates like Acquisition does for valuing the sum of all your currency.

**Comment by Tonexus** [comment]
That sounds like a good temporary measure. I'll work on adding those to the config file.

**Comment by kazuoteramoto** [comment]
poe.ninja have this endpoint for currency:
`http://poe.ninja/api/Data/GetCurrencyOverview?league={}` (with the usual league name from GGG, you can also use `tmpstandard` and `tmphardcore`)

Its provide chaos equivalent and the values show in the site in a json file. I remember the dev of poe.ninja giving this link to some tool dev and many tools use it, but I don't know what is the official usage policy.

**Comment by Tonexus** [comment]
I'll check it out. Does the ninja dev have any official documentation for his API? I only found out about  next change id a week into my program.

**Comment by Tonexus** [comment]
Added automatic exchange rates from poe.ninja.

**Comment by rushtothesun** [comment]
Please consider making an option to turn this off

**Comment by Tonexus** [comment]
Hmm, what's your reasoning? I am planning to add a button to manually refresh the exchange rates, so maybe I'll turn off the initial parse.

**Comment by rushtothesun** [comment]
It's pretty annoying to be dealing with chaos and then see results like 9 alchs or 8 fusing.  An option to only display results in the currency selected seems pretty natural.
