### ISSUE TITLE
Allow Corrupted 

### ISSUE THREAD

**Issue by gdneye** [Tonexus/poe-scambot#5]
Edit: Deleted information that would be more appropriate in other threads.

Hey, first off thanks for making this!  The app is extremely quick and works nicely.  

I've noticed that the "Allow Corrupted" toggle does not seem to work properly.  I have searched for enlighten supports with the "Allow Corrupted" toggled to off.  When I do that the app will show me both regular and corrupted enlighten gems.  I've tested the toggle both on and off (using my own enlighten gem to force a response from the app).  Both settings result in a beep when I update the information on my corrupted gem (by moving it around and changing zones or w/e).  
 
On that note, do you have any idea of how much complicated regex searches will slow the app down?  Here is an example of my output (if there are any errors ignore them, I'm still working on getting the excel formulas perfected).  

(((Goldwyrm).+(([2][5-9])|([3][0]))% increased Quantity of Items found)|(((Andvarius).+(([6][7-9])|([7][0]))% increased Rarity of items found)|((([5][1-6])% Increased Energy Shield).+(([1][6-7])% to maximum Energy Shield))|(enlighten support)

**Comment by Tonexus** [comment]
I'll check on the "allow corrupted" option.

I am currently working on the multisearch idea, and I am exploring options that don't need extra windows. The regex should be fine, as the item texts are fairly short, and you're not doing anything anything too weird (think "(x+x+)+"). If you have any further comments about the other issues, please put them in the appropriate issue threads.

**Comment by gdneye** [comment]
I've been slowly messing around with the code over the last few weeks and I figured out what was wrong.  The code currently reads, 

        if not self.corrupted and item['corrupted'] == 'True':

I replaced that code with the following and I believe it is working correctly.

        if self.corrupted == False and item['corrupted'] == True:
