### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by gdneye** [Tonexus/poe-scambot#6]
I'm interested in including the object price as part of the searchable regex.  This will allow me to set up multiple searches at different price points e.g.
(Goldwyrm.+[0-5] chaos.+(2[7-9]|30)% increased Q).+(Energy From Within.+[0-10] chaos.+6% increased).

Below is what I've attempted to do, it might help clarify what I'm asking, but on the other hand you may have a simple answer to my request and not need it.

Thanks,
Tim

I've attempted to modify the code myself to accomplish this, but I have no experience in Python and limited self-taught experience in any coding (PHP, JS, SQL, HTML, VBA).  

My basic attempt was to make a couple of changes to the parserthread.pyw file.

1) I moved the code that sets the "price_regex_match" variable above the code that sets the "full_name" and "full_text" variable.  I tested scambot after this step and was unable to notice any changes, it appeared to be working as intended.

2) I changed the full_text variable from

        full_text = ' '.join([full_name] + (item['implicitMods'] if 'implicitMods' in item else []) + (item['explicitMods'] if 'explicitMods' in item else []))

to

        full_text = ' '.join([price_regex_match] + [full_name] + (item['implicitMods'] if 'implicitMods' in item else []) + (item['explicitMods'] if 'explicitMods' in item else []))

I've tried a few other iterations replacing "price_regex_match" with "price_regex.match", "price_regex", "price_regex_match.group(2)", etc.  Always the same issue as follows.

I tested after this change and the program appeared to be working normally, but would not return any results.  It loads, starts, stops, allows me to adjust settings, gives the message that it is parsing threads and moves to subsequent threads successfully. 

I left the regex field blank for this search and made the other settings extremely broad.  Before change #2 such an identically broad search would result in hundreds of beeps within a second or two.  After the change it will go minutes with no beeps, so I appear to be doing something that makes the regex unreadable, or causes it to fail the "if not self.regex.search(full_text)" line of code.

My main guess is that I am calling the variable wrong or that I need to convert the variable to a string, but I don't know how to fix either.

Thanks again

**Comment by Tonexus** [comment]
I've been busy and haven't looked at the code in a while, but from memory it should be something like

`[str(price_regex_match.group(2))]`

I think your issue is that you're not casting the int to a string. But note that this does not include the currency type (chaos, exalted, etc).

I think that you'd want something more like 

`[str(price_regex_match.group(2)), price_regex_match.group(3)]`

**Comment by gdneye** [comment]
Thanks, this worked!
